CREATE DATABASE IF NOT EXISTS ECOMMERCE;

/* SELECT DATABSE TO USE */
USE ECOMMERCE;

/* CREATE TABLE members*/
CREATE TABLE IF NOT EXISTS categories (
category_id int PRIMARY KEY AUTO_INCREMENT,
category_nm VARCHAR(50),
parent_id int
);